version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates managed by GitHub Actions once a month
      interval: "monthly"
    groups:
      # Group together all dependencies in a single pull request
      dependencies:
        patterns:
          - "*"
