stages:
    - test
    - publish

default:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    cache:
        key:
            files:
                - src/SteamCollectionDownloadSizeCalculator.csproj
                - tests/SteamCollectionDownloadSizeCalculatorTests.csproj
        paths:
            - .nuget/packages/
        policy: pull-push

variables:
    OUTPUT_DIR: publish/$FRAMEWORK/$RUNTIME/

test:
    stage: test
    script:
        - dotnet test tests/SteamCollectionDownloadSizeCalculatorTests.csproj -c Release --verbosity normal -f net10.0

publish:
    stage: publish
    parallel:
        matrix:
            - RUNTIME: ["linux-x64", "linux-arm64", "osx-x64", "osx-arm64", "win-x64", "win-arm64"]
    script:
        - dotnet publish src/SteamCollectionDownloadSizeCalculator.csproj -c Release -f net10.0 -r $RUNTIME -o $OUTPUT_DIR --nologo --self-contained
    artifacts:
        name: $RUNTIME
        paths:
            - $OUTPUT_DIR
        expire_in: 1 hour